//
export const functions = [
      { value: '', label: 'All' },
      { value: 'Admin', label: 'Admin' },
      { value: 'Finance', label: 'Finance' },
      { value: 'General', label: 'General' },
      { value: 'Human Resources', label: 'Human Resources' },
      { value: 'IT', label: 'IT' },
      { value: 'Marketing', label: 'Marketing' },
      { value: 'Procurement', label: 'Procurement' },
      { value: 'Sales', label: 'Sales' },
      { value: 'Legal and Compliance', label: 'Legal and Compliance' },
];
export const employeeRanges = [
      { value: '', label: 'All' },
      { value: '1-50', label: '1-50' },
      { value: '51-100', label: '51-100' },
      { value: '101-250', label: '101-250' },
      { value: '251-500', label: '251-500' },
      { value: '501-1,000', label: '501-1,000' },
      { value: '>1,000', label: '>1,000' },
];
export const seniorityLevels = [
      { value: '', label: 'All' },
      { value: 'C-Level', label: 'C-Level' },
      { value: 'VP-Level', label: 'VP-Level' },
      { value: 'Director', label: 'Director' },
      { value: 'Manager', label: 'Manager' },
      { value: 'Non-Manager', label: 'Non-Manager' },
];
export const primaryIndustries = [
      { value: '', label: 'All' },
      { value: 'Agriculture', label: 'Agriculture' },
      { value: 'Business Services', label: 'Business Services' },
      { value: 'Construction', label: 'Construction' },
      { value: 'Consumer Services', label: 'Consumer Services' },
      { value: 'Education', label: 'Education' },
      { value: 'Energy, Utilities & Waste', label: 'Energy, Utilities & Waste' },
      { value: 'Finance', label: 'Finance' },
      { value: 'Government', label: 'Government' },
      { value: 'Healthcare Services', label: 'Healthcare Services' },
      { value: 'Holding Companies & Conglomerates', label: 'Holding Companies & Conglomerates' },
      { value: 'Hospitality', label: 'Hospitality' },
      { value: 'Hospitals & Physicians Clinics', label: 'Hospitals & Physicians Clinics' },
      { value: 'Insurance', label: 'Insurance' },
      { value: 'Law Firms & Legal Services', label: 'Law Firms & Legal Services' },
      { value: 'Manufacturing', label: 'Manufacturing' },
      { value: 'Media & Internet', label: 'Media & Internet' },
      { value: 'Minerals & Mining', label: 'Minerals & Mining' },
      { value: 'Organizations', label: 'Organizations' },
      { value: 'Real Estate', label: 'Real Estate' },
      { value: 'Retail', label: 'Retail' },
      { value: 'Software', label: 'Software' },
      { value: 'Telecommunications', label: 'Telecommunications' },
      { value: 'Transportation', label: 'Transportation' },
];
export const subIndustries = [
      { value: '', label: 'All' },
      { value: 'Animals & Livestock', label: 'Animals & Livestock' },
      { value: 'Crops', label: 'Crops' },
      { value: 'Forestry', label: 'Forestry' },
      { value: 'Accounting Services', label: 'Accounting Services' },
      { value: 'Advertising & Marketing', label: 'Advertising & Marketing' },
      { value: 'Call Centers & Business Centers', label: 'Call Centers & Business Centers' },
      { value: 'Chambers of Commerce', label: 'Chambers of Commerce' },
      { value: 'Commercial Printing', label: 'Commercial Printing' },
      { value: 'Custom Software & IT Services', label: 'Custom Software & IT Services' },
      { value: 'Debt Collection', label: 'Debt Collection' },
      { value: 'Facilities Management & Commercial Cleaning', label: 'Facilities Management & Commercial Cleaning' },
      { value: 'Food Service', label: 'Food Service' },
      { value: 'HR & Staffing', label: 'HR & Staffing' },
      { value: 'Information & Document Management', label: 'Information & Document Management' },
      { value: 'Management Consulting', label: 'Management Consulting' },
      { value: 'Multimedia & Graphic Design', label: 'Multimedia & Graphic Design' },
      { value: 'Research & Development', label: 'Research & Development' },
      { value: 'Security Products & Services', label: 'Security Products & Services' },
      { value: 'Translation & Linguistic Services', label: 'Translation & Linguistic Services' },
      { value: 'Architecture, Engineering & Design', label: 'Architecture, Engineering & Design' },
      { value: 'Civil Engineering Construction', label: 'Civil Engineering Construction' },
      { value: 'Commercial & Residential Construction', label: 'Commercial & Residential Construction' },
      { value: 'Automotive Service & Collision Repair', label: 'Automotive Service & Collision Repair' },
      { value: 'Barber Shops & Beauty Salons', label: 'Barber Shops & Beauty Salons' },
      { value: 'Car & Truck Rental', label: 'Car & Truck Rental' },
      { value: 'Childcare', label: 'Childcare' },
      { value: 'Cleaning Services', label: 'Cleaning Services' },
      { value: 'Funeral Homes & Funeral Related Services', label: 'Funeral Homes & Funeral Related Services' },
      { value: 'Landscape Services', label: 'Landscape Services' },
      { value: 'Photography Studio', label: 'Photography Studio' },
      { value: 'Repair Services', label: 'Repair Services' },
      { value: 'Weight & Health Management', label: 'Weight & Health Management' },
      { value: 'Colleges & Universities', label: 'Colleges & Universities' },
      { value: 'K-12 Schools', label: 'K-12 Schools' },
      { value: 'Training', label: 'Training' },
      { value: 'Electricity, Oil & Gas', label: 'Electricity, Oil & Gas' },
      { value: 'Oil & Gas Exploration & Services', label: 'Oil & Gas Exploration & Services' },
      {
            value: 'Waste Treatment, Environmental Services & Recycling',
            label: 'Waste Treatment, Environmental Services & Recycling',
      },
      { value: 'Water Treatment', label: 'Water Treatment' },
      { value: 'Banking', label: 'Banking' },
      { value: 'Credit Cards & Transaction Processing', label: 'Credit Cards & Transaction Processing' },
      { value: 'Investment Banking', label: 'Investment Banking' },
      { value: 'Lending & Brokerage', label: 'Lending & Brokerage' },
      { value: 'Venture Capital & Private Equity', label: 'Venture Capital & Private Equity' },
      { value: 'Federal', label: 'Federal' },
      { value: 'Local', label: 'Local' },
      { value: 'State', label: 'State' },
      { value: 'Tribal Nations', label: 'Tribal Nations' },
      { value: 'Ambulance Services', label: 'Ambulance Services' },
      { value: 'Blood & Organ Banks', label: 'Blood & Organ Banks' },
      { value: 'Elderly Care Services', label: 'Elderly Care Services' },
      { value: 'Medical Laboratories & Imaging Centers', label: 'Medical Laboratories & Imaging Centers' },
      { value: 'Mental Health & Rehabilitation Facilities', label: 'Mental Health & Rehabilitation Facilities' },
      { value: 'Veterinary Services', label: 'Veterinary Services' },
      { value: 'Amusement Parks, Arcades & Attractions', label: 'Amusement Parks, Arcades & Attractions' },
      { value: 'Cultural & Informational Centers', label: 'Cultural & Informational Centers' },
      { value: 'Fitness & Dance Facilities', label: 'Fitness & Dance Facilities' },
      { value: 'Gambling & Gaming', label: 'Gambling & Gaming' },
      { value: 'Libraries', label: 'Libraries' },
      { value: 'Lodging & Resorts', label: 'Lodging & Resorts' },
      { value: 'Movie Theaters', label: 'Movie Theaters' },
      { value: 'Museums & Art Galleries', label: 'Museums & Art Galleries' },
      { value: 'Performing Arts Theaters', label: 'Performing Arts Theaters' },
      { value: 'Restaurants', label: 'Restaurants' },
      { value: 'Sports Teams & Leagues', label: 'Sports Teams & Leagues' },
      { value: 'Travel Agencies & Services', label: 'Travel Agencies & Services' },
      { value: 'Zoos & National Parks', label: 'Zoos & National Parks' },
      { value: 'Dental Offices', label: 'Dental Offices' },
      { value: 'Medical & Surgical Hospitals', label: 'Medical & Surgical Hospitals' },
      { value: 'Medical Specialists', label: 'Medical Specialists' },
      { value: 'Physicians Clinics', label: 'Physicians Clinics' },
      { value: 'Aerospace & Defense', label: 'Aerospace & Defense' },
      { value: 'Appliances', label: 'Appliances' },
      { value: 'Automotive Parts', label: 'Automotive Parts' },
      { value: 'Boats & Submarines', label: 'Boats & Submarines' },
      { value: 'Building Materials', label: 'Building Materials' },
      { value: 'Chemicals & Related Products', label: 'Chemicals & Related Products' },
      { value: 'Cleaning Products', label: 'Cleaning Products' },
      { value: 'Computer Equipment & Peripherals', label: 'Computer Equipment & Peripherals' },
      {
            value: 'Cosmetics, Beauty Supply & Personal Care Products',
            label: 'Cosmetics, Beauty Supply & Personal Care Products',
      },
      { value: 'Electronics', label: 'Electronics' },
      { value: 'Food & Beverage', label: 'Food & Beverage' },
      { value: 'Furniture', label: 'Furniture' },
      { value: 'Glass & Clay', label: 'Glass & Clay' },
      { value: 'Hand, Power & Lawn-care Tools', label: 'Hand, Power & Lawn-care Tools' },
      { value: 'Health & Nutrition Products', label: 'Health & Nutrition Products' },
      { value: 'Household & Personal Products', label: 'Household & Personal Products' },
];
export const sources = [
      { value: '', label: 'All' },
      { value: 'Zoominfo', label: 'Zoominfo' },
      { value: 'LinkedIn', label: 'LinkedIn' },
      { value: 'HKTDC', label: 'HKTDC' },
      { value: 'Reachin', label: 'Reachin' },
];
export const revenueRanges = [
      { value: '', label: 'All' },
      { value: '$1 bil. - $5 bil.', label: '$1 bil. - $5 bil.' },
      { value: '$1 mil. - $5 mil.', label: '$1 mil. - $5 mil.' },
      { value: '$10 mil. - $25 mil.', label: '$10 mil. - $25 mil.' },
      { value: '$100 mil. - $250 mil.', label: '$100 mil. - $250 mil.' },
      { value: '$25 mil. - $50 mil.', label: '$25 mil. - $50 mil.' },
      { value: '$250 mil. - $500 mil.', label: '$250 mil. - $500 mil.' },
      { value: '$5 mil. - $10 mil.', label: '$5 mil. - $10 mil.' },
      { value: '$50 mil. - $100 mil.', label: '$50 mil. - $100 mil.' },
      { value: '$500 mil. - $1 bil.', label: '$500 mil. - $1 bil.' },
      { value: '$500,000 - $1 mil.', label: '$500,000 - $1 mil.' },
      { value: 'Over $5 bil.', label: 'Over $5 bil.' },
      { value: 'Under $500,000', label: 'Under $500,000' },
];
export const companyTypes = [
      { value: '', label: 'All' },
      { value: 'Partnership Independent', label: 'Partnership Independent' },
      { value: 'Partnership Parent Headquarters', label: 'Partnership Parent Headquarters' },
      { value: 'Private Independent', label: 'Private Independent' },
      { value: 'Private Independent Headquarters', label: 'Private Independent Headquarters' },
      { value: 'Private Parent', label: 'Private Parent' },
      { value: 'Private Parent Headquarters', label: 'Private Parent Headquarters' },
      { value: 'Public Independent', label: 'Public Independent' },
      { value: 'Public Parent Headquarters', label: 'Public Parent Headquarters' },
];

export const sales = [
      { value: '', label: 'All' },
      { value: '999', label: '0-999K' },
      { value: '1', label: '0.1M-1M' },
      { value: '10', label: '1.1M-10M' },
      { value: '50', label: '11M-50M' },
      { value: '100', label: '51M-100M' },
];
export const regions = [
      { value: '', label: 'All' },
      { value: 'Algeria', label: 'Algeria' },
      { value: 'Angola', label: 'Angola' },
      { value: 'Benin', label: 'Benin' },
      { value: 'Botswana', label: 'Botswana' },
      { value: 'Burkina Faso', label: 'Burkina Faso' },
      { value: 'Burundi', label: 'Burundi' },
      { value: 'Cameroon', label: 'Cameroon' },
      { value: 'Cape Verde', label: 'Cape Verde' },
      { value: 'Central African Republic', label: 'Central African Republic' },
      { value: 'Chad', label: 'Chad' },
      { value: 'Comoros', label: 'Comoros' },
      { value: 'Congo (DRC)', label: 'Congo (DRC)' },
      { value: 'Congo (Republic)', label: 'Congo (Republic)' },
      { value: 'Djibouti', label: 'Djibouti' },
      { value: 'Egypt', label: 'Egypt' },
      { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
      { value: 'Eritrea', label: 'Eritrea' },
      { value: 'Ethiopia', label: 'Ethiopia' },
      { value: 'Gabon', label: 'Gabon' },
      { value: 'Gambia', label: 'Gambia' },
      { value: 'Ghana', label: 'Ghana' },
      { value: 'Guinea', label: 'Guinea' },
      { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
      { value: 'Kenya', label: 'Kenya' },
      { value: 'Lesotho', label: 'Lesotho' },
      { value: 'Liberia', label: 'Liberia' },
      { value: 'Libya', label: 'Libya' },
      { value: 'Madagascar', label: 'Madagascar' },
      { value: 'Malawi', label: 'Malawi' },
      { value: 'Mali', label: 'Mali' },
      { value: 'Mauritania', label: 'Mauritania' },
      { value: 'Mauritius', label: 'Mauritius' },
      { value: 'Morocco', label: 'Morocco' },
      { value: 'Mozambique', label: 'Mozambique' },
      { value: 'Namibia', label: 'Namibia' },
      { value: 'Niger', label: 'Niger' },
      { value: 'Nigeria', label: 'Nigeria' },
      { value: 'Rwanda', label: 'Rwanda' },
      { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
      { value: 'Senegal', label: 'Senegal' },
      { value: 'Seychelles', label: 'Seychelles' },
      { value: 'Sierra Leone', label: 'Sierra Leone' },
      { value: 'Somalia', label: 'Somalia' },
      { value: 'South Africa', label: 'South Africa' },
      { value: 'Sudan', label: 'Sudan' },
      { value: 'Swaziland', label: 'Swaziland' },
      { value: 'Tanzania', label: 'Tanzania' },
      { value: 'Togo', label: 'Togo' },
      { value: 'Tunisia', label: 'Tunisia' },
      { value: 'Uganda', label: 'Uganda' },
      { value: 'Zambia', label: 'Zambia' },
      { value: 'Zimbabwe', label: 'Zimbabwe' },

      { value: 'Afghanistan', label: 'Afghanistan' },
      { value: 'Armenia', label: 'Armenia' },
      { value: 'Azerbaijan', label: 'Azerbaijan' },
      { value: 'Bahrain', label: 'Bahrain' },
      { value: 'Bangladesh', label: 'Bangladesh' },
      { value: 'Bhutan', label: 'Bhutan' },
      { value: 'Brunei Darussalam', label: 'Brunei Darussalam' },
      { value: 'Cambodia', label: 'Cambodia' },
      { value: 'China', label: 'China' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'Hong Kong', label: 'Hong Kong' },
      { value: 'India', label: 'India' },
      { value: 'Indonesia', label: 'Indonesia' },
      { value: 'Iran', label: 'Iran' },
      { value: 'Israel', label: 'Israel' },
      { value: 'Japan', label: 'Japan' },
      { value: 'Jordan', label: 'Jordan' },
      { value: 'Kazakhstan', label: 'Kazakhstan' },
      { value: 'Kuwait', label: 'Kuwait' },
      { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
      { value: 'Laos', label: 'Laos' },
      { value: 'Lebanon', label: 'Lebanon' },
      { value: 'Malaysia', label: 'Malaysia' },
      { value: 'Maldives', label: 'Maldives' },
      { value: 'Mongolia', label: 'Mongolia' },
      { value: 'Myanmar', label: 'Myanmar' },
      { value: 'Nepal', label: 'Nepal' },
      { value: 'North Korea', label: 'North Korea' },
      { value: 'Oman', label: 'Oman' },
      { value: 'Pakistan', label: 'Pakistan' },
      { value: 'Philippines', label: 'Philippines' },
      { value: 'Qatar', label: 'Qatar' },
      { value: 'Saudi Arabia', label: 'Saudi Arabia' },
      { value: 'Singapore', label: 'Singapore' },
      { value: 'South Korea', label: 'South Korea' },
      { value: 'Sri Lanka', label: 'Sri Lanka' },
      { value: 'Syria', label: 'Syria' },
      { value: 'Taiwan', label: 'Taiwan' },
      { value: 'Tajikistan', label: 'Tajikistan' },
      { value: 'Thailand', label: 'Thailand' },
      { value: 'Turkey', label: 'Turkey' },
      { value: 'Turkmenistan', label: 'Turkmenistan' },
      { value: 'United Arab Emirates', label: 'United Arab Emirates' },
      { value: 'Uzbekistan', label: 'Uzbekistan' },
      { value: 'Vietnam', label: 'Vietnam' },

      { value: 'Albania', label: 'Albania' },
      { value: 'Andorra', label: 'Andorra' },
      { value: 'Austria', label: 'Austria' },
      { value: 'Belarus', label: 'Belarus' },
      { value: 'Belgium', label: 'Belgium' },
      { value: 'Bosnia Herzegovina', label: 'Bosnia Herzegovina' },
      { value: 'Bulgaria', label: 'Bulgaria' },
      { value: 'Croatia', label: 'Croatia' },
      { value: 'Cyprus', label: 'Cyprus' },
      { value: 'Czech Republic', label: 'Czech Republic' },
      { value: 'Denmark', label: 'Denmark' },
      { value: 'Estonia', label: 'Estonia' },
      { value: 'Finland', label: 'Finland' },
      { value: 'France', label: 'France' },
      { value: 'Germany', label: 'Germany' },
      { value: 'Greece', label: 'Greece' },
      { value: 'Hungary', label: 'Hungary' },
      { value: 'Iceland', label: 'Iceland' },
      { value: 'Ireland', label: 'Ireland' },
      { value: 'Italy', label: 'Italy' },
      { value: 'Latvia', label: 'Latvia' },
      { value: 'Liechtenstein', label: 'Liechtenstein' },
      { value: 'Lithuania', label: 'Lithuania' },
      { value: 'Luxembourg', label: 'Luxembourg' },
      { value: 'Malta', label: 'Malta' },
      { value: 'Moldova', label: 'Moldova' },
      { value: 'Monaco', label: 'Monaco' },
      { value: 'Netherlands', label: 'Netherlands' },
      { value: 'North Macedonia (FYROM)', label: 'North Macedonia (FYROM)' },
      { value: 'Norway', label: 'Norway' },
      { value: 'Poland', label: 'Poland' },
      { value: 'Portugal', label: 'Portugal' },
      { value: 'Romania', label: 'Romania' },
      { value: 'Russia', label: 'Russia' },
      { value: 'San Marino', label: 'San Marino' },
      { value: 'Slovakia', label: 'Slovakia' },
      { value: 'Slovenia', label: 'Slovenia' },
      { value: 'Spain', label: 'Spain' },
      { value: 'Sweden', label: 'Sweden' },
      { value: 'Switzerland', label: 'Switzerland' },
      { value: 'Ukraine', label: 'Ukraine' },
      { value: 'United Kingdom', label: 'United Kingdom' },

      { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
      { value: 'Bahamas', label: 'Bahamas' },
      { value: 'Barbados', label: 'Barbados' },
      { value: 'Belize', label: 'Belize' },
      { value: 'Canada', label: 'Canada' },
      { value: 'Costa Rica', label: 'Costa Rica' },
      { value: 'Cuba', label: 'Cuba' },
      { value: 'Dominica', label: 'Dominica' },
      { value: 'Dominican Republic', label: 'Dominican Republic' },
      { value: 'El Salvador', label: 'El Salvador' },
      { value: 'Grenada', label: 'Grenada' },
      { value: 'Guatemala', label: 'Guatemala' },
      { value: 'Haiti', label: 'Haiti' },
      { value: 'Honduras', label: 'Honduras' },
      { value: 'Jamaica', label: 'Jamaica' },
      { value: 'Mexico', label: 'Mexico' },
      { value: 'Nicaragua', label: 'Nicaragua' },
      { value: 'Panama', label: 'Panama' },
      { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
      { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
      { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
      { value: 'United States', label: 'United States' },

      { value: 'Australia', label: 'Australia' },
      { value: 'Cook Islands', label: 'Cook Islands' },
      { value: 'Fiji', label: 'Fiji' },
      { value: 'Kiribati', label: 'Kiribati' },
      { value: 'New Zealand', label: 'New Zealand' },
      { value: 'Papua New Guinea', label: 'Papua New Guinea' },
      { value: 'Samoa', label: 'Samoa' },
      { value: 'Solomon Islands', label: 'Solomon Islands' },
      { value: 'Timor-Leste', label: 'Timor-Leste' },
      { value: 'Tonga', label: 'Tonga' },
      { value: 'Vanuatu', label: 'Vanuatu' },

      { value: 'Argentina', label: 'Argentina' },
      { value: 'Bolivia', label: 'Bolivia' },
      { value: 'Brazil', label: 'Brazil' },
      { value: 'Chile', label: 'Chile' },
      { value: 'Colombia', label: 'Colombia' },
      { value: 'Ecuador', label: 'Ecuador' },
      { value: 'Guyana', label: 'Guyana' },
      { value: 'Paraguay', label: 'Paraguay' },
      { value: 'Peru', label: 'Peru' },
      { value: 'Suriname', label: 'Suriname' },
      { value: 'Uruguay', label: 'Uruguay' },
      { value: 'Venezuela', label: 'Venezuela' },
];

//
export const industryOptions = [
      { label: 'Technology', value: 'Technology' },
      { label: 'Finance', value: 'Finance' },
      { label: 'Healthcare', value: 'Healthcare' },
      { label: 'Education', value: 'Education' },
      { label: 'Retail', value: 'Retail' },
];

export const managementLevelOptions = [
      { label: 'Executive', value: 'Executive' },
      { label: 'Manager', value: 'Manager' },
      { label: 'Supervisor', value: 'Supervisor' },
      { label: 'Employee', value: 'Employee' },
];

export const departmentOptions = [
      { label: 'Engineering', value: 'Engineering' },
      { label: 'Sales', value: 'Sales' },
      { label: 'HR', value: 'HR' },
      { label: 'Marketing', value: 'Marketing' },
      { label: 'Operations', value: 'Operations' },
];

export const jobFunctionOptions = [
      { label: 'Development', value: 'Development' },
      { label: 'Support', value: 'Support' },
      { label: 'Analysis', value: 'Analysis' },
      { label: 'Consulting', value: 'Consulting' },
      { label: 'Design', value: 'Design' },
];

export const titleOptions = [
      { label: 'Software Engineer', value: 'Software Engineer' },
      { label: 'Project Manager', value: 'Project Manager' },
      { label: 'HR Specialist', value: 'HR Specialist' },
      { label: 'Marketing Lead', value: 'Marketing Lead' },
      { label: 'Operations Head', value: 'Operations Head' },
];

export const Year = [
      { label: 2018, value: 2018 },
      { label: 2019, value: 2019 },
      { label: 2020, value: 2020 },
      { label: 2021, value: 2021 },
      { label: 2022, value: 2022 },
      { label: 2023, value: 2023 },
      { label: 2024, value: 2024 },
      { label: 2025, value: 2025 },
      { label: 2026, value: 2026 },
      { label: 2027, value: 2027 },
      { label: 2028, value: 2028 },
      { label: 2029, value: 2029 },
      { label: 2030, value: 2030 },
      { label: 2031, value: 2031 },
      { label: 2032, value: 2032 },
      { label: 2033, value: 2033 },
      { label: 2034, value: 2034 },
      { label: 2035, value: 2035 },
];

export const blogCategory = ['Privacy / Data', 'Marketing Operation', 'Sales Operation', 'HR'];
